let data = [
  "Act for Nature",
  "Color of Water",
  "Current Events",
  "Wallpapers",
  "3D Renders",
  "Textures & Patterns",
  "Experimental",
  "Architecture",
  "Nature",
  "Business & Work",
  "Fashion",
  "Film",
  "Food & Drink",
  "Health & Wellness",
  "People",
  "Interiors",
  "Street Photography",
  "Travel",
  "Animals",
  "Spirituality",
  "Arts & Culture",
  "History",
  "Athletics",
];

let link = [
  "act-for-nature",
  "color-of-water",
  "current-events",
  "wallpapers",
  "3d-renders",
  "textures-patterns",
  "experimental",
  "architecture",
  "nature",
  "business-work",
  "fashion",
  "film",
  "food-drink",
  "health",
  "people",
  "interiors",
  "street-photography",
  "travel",
  "animals",
  "spirituality",
  "arts-culture",
  "history",
  "athletics",
];
export { data, link };
