let data = [
  "Act for Nature",
  "Color of Water",
  "Current Events",
  "Wallpapers",
  "3D Renders",
  "Textures & Patterns",
  "Experimental",
  "Architecture",
  "Nature",
  "Business & Work",
  "Fashion",
  "Film",
  "Food & Drink",
  "Health & Wellness",
  "People",
  "Interiors",
  "Street Photography",
  "Travel",
  "Animals",
  "Spirituality",
  "Arts & Culture",
  "History",
  "Athletics",
];

export { data };
