let data = [
  "Act for Nature",
  "Color of Water",
  "Current Events",
  "Wallpapers",
  "3D Renders",
  "Textures & Patterns",
  "Experimental",
  "Architecture",
  "Nature",
  "Business & Work",
  "Fashion",
  "Film",
  "Food & Drink",
  "Health & Wellness",
  "People",
  "Interiors",
  "Street Photography",
  "Travel",
  "Animals",
  "Spirituality",
  "Arts & Culture",
  "History",
  "Athletics",
];

let para1 = [
  "It's time to reveal dirty water’s true colors. We’re teaming up with charity: water to raise awareness for the 771 million people who lack access to clean and safe drinking water today. Submit your most striking.It (of any subject matter) to match the colors of dirty water.",
  "Submit powerful nature shots showcasing the landscapes you still want to be around 50 years from now. The top 15 submissions that best reflect the beauty of our planet to be featured in an online gallery on the UNEP website.",
  "Covering the latest important events, news-worthy moments and movements from around the world — from political protests to cultural celebrations. When submitting,",
  "For the first time ever, Unsplash is accepting a new category of images outside of photography. Submit your 3-dimensional images, designed in the software of your choice, rendered into JPEG images.",
  "Let’s celebrate the magic of Mother Earth — with images of everything our planet has to offer, from stunning seascapes, starry skies, and everything in between.",
  "Beautiful analog photography from the past and present day — featuring polaroids, black and white images, grainy portraits, and more.",
  "Ready, set, snap. Capturing action in the every day — from the tough gym workouts to the tense basketball games out on the court.",
];
let para2 = [
  " YELLOW, RED, BROWN, GREEN, or GRAY images, Our friends at Boxed Water are donating $1 per approved submission.",
  "This year marks UNEP’s 50th birthday, and they’ve asked the Unsplash community to take part in celebrating.",
  "please provide a photo description so we understand the full context of the image.",
  "Our 3D Renders Club has a 'Minimal Blender Backgrounds' challenge currently running.",
  "from brutalist buildings to minimalist structures that will give you a new appreciation for the art of architecture.",
  "Our Film Club has a 'distressed negatives' challenge currently running",
  "Your daily dose of culture — with photography showcasing the best in art, music and literature from around the world.",
];
export { data, para1, para2 };
